### ISSUE TITLE
Support for OpenShift Platform 4.5 / 4.6?

### ISSUE THREAD

**Issue by mschindl** [HewlettPackard/OpenShift-on-SimpliVity#103]
Hello,
will you support OpenShift Platform 4.5 / 4.6 in the near future?

Best regards, Marc

**Comment by arilivigni** [comment]
https://www.crn.com/news/data-center/hpe-simplivity-146-layoffs-confirmed-warn-notice#:~:text=Hewlett%20Packard%20Enterprise%20has%20laid,the%20week%20of%20July%2024.
